import Header from '@/components/Header'
import Nav from '@/components/Nav'
import Results from '@/components/Results'
// import VideoContainer from '@/components/VideoContainer'
import requests from '@/utils/requests'
import Head from 'next/head'

export default function Home({ title, results, IMAGES, BASE_URL }) {

  return (
    <div>
      <Head>
        <title>{`Hulu 2.0 - ${title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header IMAGES={IMAGES} />
      <Nav />
      {/* <VideoContainer src={show} /> */}
      <Results results={results} BASE_URL={BASE_URL} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre
  const IMAGES = process.env.IMAGES
  const BASE_URL = process.env.TUTORIALS

  // const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then((res) => res.json())

  const request = await fetch(`http://localhost:3000${requests[genre]?.url || requests.fetchAngular.url}`).then((res) => res.json())

  return {
    props: {
      title: requests[genre]?.title || requests.fetchAngular.title,
      results: request.results,
      IMAGES: IMAGES,
      BASE_URL: BASE_URL
    }
  }
}