import { signIn } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/legacy/image'

function Login() {
  return (
    <>
      <Head>
        <title>Facebook App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-10 grid place-items-center">
        <Image src='http://localhost:8080/SourceFiles/images/facebook.png' width={100} height={100} unoptimized alt='' />
        <h1 onClick={signIn} className="mt-10 p-5 bg-blue-500 rounded-full text-white text-center cursor-pointer">Login with Facebook</h1>
      </div>
    </>
  )
}

export default Login